const namingI18n={
  zh:{eyebrow:'外国人中文取名',heading:'让名字既能被叫出来，<br>也能讲述你的中国故事。',lead:'结合原名发音、生日九数、中国农历年干五行与个人愿景，生成三个中文名字初选，并用《孙子兵法》解释名字对应的行动战略。',original:'原文姓名',birth:'出生日期',intent:'希望名字表达',intents:['领导与开创','合作与和谐','智慧与洞察','勇气与行动','丰盛与贡献'],submit:'生成中文名初选 →',privacy:'资料仅在本页计算，不会上传或保存。',context:'命名文化坐标',candidate:'候选名',war:'孙子兵法 · 名字战略',review:'正式使用前人工复核',reviewCopy:'候选名需要进一步检查普通话和目标方言谐音、性别与年龄语感、常见重名、职业场景及证件登记需要。五行归类在不同流派中可能不同。',system:'九数',year:'农历年象',continuation:'象征延展',sound:'姓氏取原名首音作为起点',notBazi:'这是文化命名初选，不是完整八字取名。'},
  en:{eyebrow:'Chinese naming for global citizens',heading:'A name that can be spoken<br>and can tell your China story.',lead:'Three Chinese-name starting points based on original pronunciation, the primary nine number, the lunar-year stem element and your intention—with an Art of War strategy for each.',original:'Original name',birth:'Date of birth',intent:'What should the name express?',intents:['Leadership & initiative','Harmony & collaboration','Wisdom & insight','Courage & action','Abundance & contribution'],submit:'Generate name candidates →',privacy:'Calculated only on this page. Nothing is uploaded or stored.',context:'Naming coordinates',candidate:'Candidate',war:'The Art of War · name strategy',review:'Human review before real-world use',reviewCopy:'Check Mandarin and target-dialect homophones, age and gender tone, duplication, professional context and identity-document needs. Element classifications vary across naming traditions.',system:'Nine number',year:'Lunar-year symbol',continuation:'Symbolic continuation',sound:'Surname begins from the original sound',notBazi:'A cultural naming shortlist—not a complete BaZi naming service.'},
  es:{eyebrow:'Nombres chinos para extranjeros',heading:'Un nombre que pueda pronunciarse<br>y contar tu historia con China.',lead:'Tres puntos de partida según pronunciación original, número principal, elemento del año lunar e intención, con una estrategia de El arte de la guerra.',original:'Nombre original',birth:'Fecha de nacimiento',intent:'¿Qué debe expresar?',intents:['Liderazgo e iniciativa','Armonía y colaboración','Sabiduría y visión','Valor y acción','Abundancia y contribución'],submit:'Generar nombres candidatos →',privacy:'El cálculo ocurre solo en esta página. Nada se sube ni se guarda.',context:'Coordenadas del nombre',candidate:'Candidato',war:'El arte de la guerra · estrategia del nombre',review:'Revisión humana antes del uso real',reviewCopy:'Hay que revisar homófonos en mandarín y dialectos, tono de edad y género, nombres repetidos, contexto profesional y documentos. La clasificación por elementos varía según la escuela.',system:'Número principal',year:'Símbolo del año lunar',continuation:'Continuación simbólica',sound:'El apellido parte del sonido original',notBazi:'Selección cultural inicial; no es un servicio BaZi completo.'}
};
const surnameList=[
  {re:/^[a]/i,h:'安',p:'Ān'},{re:/^[bp]/i,h:'白',p:'Bái'},{re:/^[ckg]/i,h:'高',p:'Gāo'},{re:/^[dt]/i,h:'唐',p:'Táng'},{re:/^[ei]/i,h:'易',p:'Yì'},{re:/^[fv]/i,h:'方',p:'Fāng'},{re:/^[h]/i,h:'韩',p:'Hán'},{re:/^[j]/i,h:'江',p:'Jiāng'},{re:/^[l]/i,h:'林',p:'Lín'},{re:/^[m]/i,h:'马',p:'Mǎ'},{re:/^[n]/i,h:'宁',p:'Níng'},{re:/^[ow]/i,h:'王',p:'Wáng'},{re:/^[q]/i,h:'秦',p:'Qín'},{re:/^[r]/i,h:'任',p:'Rèn'},{re:/^[sxz]/i,h:'苏',p:'Sū'},{re:/^[uy]/i,h:'俞',p:'Yú'}
];
const ch=(h,p,zh,en,es,e)=>({h,p,m:{zh,en,es},e});
const intentChars={
  leadership:[ch('弘','Hóng','弘大、开拓','expansive initiative','iniciativa amplia','火'),ch('卓','Zhuó','卓越、清晰','excellence and clarity','excelencia y claridad','火'),ch('远','Yuǎn','远见、长程','vision and reach','visión y alcance','土'),ch('拓','Tuò','开拓、行动','exploration and action','exploración y acción','火')],
  harmony:[ch('和','Hé','和合、协调','harmony and coordination','armonía y coordinación','土'),ch('宁','Níng','安宁、从容','calm and composure','calma y serenidad','土'),ch('悦','Yuè','喜悦、亲和','joy and warmth','alegría y cercanía','火'),ch('同','Tóng','同心、共识','shared purpose','propósito común','火')],
  wisdom:[ch('睿','Ruì','睿智、洞察','wisdom and insight','sabiduría y visión','金'),ch('知','Zhī','求知、明辨','knowledge and discernment','conocimiento y criterio','火'),ch('哲','Zhé','哲思、通达','thoughtful understanding','comprensión reflexiva','火'),ch('澄','Chéng','澄明、清晰','clarity and calm','claridad y calma','水')],
  courage:[ch('毅','Yì','坚毅、持久','resolve and endurance','determinación y constancia','木'),ch('勇','Yǒng','勇气、担当','courage and ownership','valor y responsabilidad','土'),ch('进','Jìn','进取、向前','forward momentum','impulso hacia delante','火'),ch('凯','Kǎi','凯旋、信心','confidence and achievement','confianza y logro','木')],
  abundance:[ch('丰','Fēng','丰盛、充实','abundance and fullness','abundancia y plenitud','火'),ch('嘉','Jiā','美好、赞许','goodness and esteem','bondad y estima','木'),ch('盛','Shèng','兴盛、充盈','flourishing energy','energía floreciente','火'),ch('恩','Ēn','感恩、惠泽','gratitude and contribution','gratitud y contribución','土')]
};
const elementChars={
  木:[ch('荣','Róng','生长、荣盛','growth and flourishing','crecimiento y florecimiento','木'),ch('柏','Bǎi','坚韧、常青','resilience and constancy','resiliencia y constancia','木'),ch('楷','Kǎi','楷范、端正','principle and integrity','principio e integridad','木'),ch('桐','Tóng','高雅、成长','grace and growth','elegancia y crecimiento','木')],
  火:[ch('明','Míng','光明、明辨','light and clarity','luz y claridad','火'),ch('昕','Xīn','黎明、新生','dawn and renewal','amanecer y renovación','火'),ch('煜','Yù','照耀、活力','radiance and vitality','brillo y vitalidad','火'),ch('晨','Chén','清晨、希望','morning and hope','mañana y esperanza','火')],
  土:[ch('安','Ān','安定、从容','stability and calm','estabilidad y calma','土'),ch('坤','Kūn','承载、厚德','support and grounded virtue','apoyo y virtud firme','土'),ch('岳','Yuè','山岳、定力','mountain strength','fuerza de montaña','土'),ch('宇','Yǔ','空间、气度','breadth and presence','amplitud y presencia','土')],
  金:[ch('钧','Jūn','平衡、分量','balance and weight','equilibrio y peso','金'),ch('铭','Míng','铭记、原则','memory and principle','memoria y principio','金'),ch('锐','Ruì','敏锐、进取','acuity and drive','agudeza e impulso','金'),ch('锦','Jǐn','美好、成就','beauty and achievement','belleza y logro','金')],
  水:[ch('泽','Zé','润泽、惠益','nourishment and benefit','nutrición y beneficio','水'),ch('涵','Hán','包容、涵养','depth and inclusion','profundidad e inclusión','水'),ch('清','Qīng','清澈、清醒','clarity and lucidity','claridad y lucidez','水'),ch('澜','Lán','波澜、远势','movement and far-reaching energy','movimiento y alcance','水')]
};
const elementCycle={木:'火',火:'土',土:'金',金:'水',水:'木'};
const cycleText={zh:{木:'木生火',火:'火生土',土:'土生金',金:'金生水',水:'水生木'},en:{木:'Wood generates Fire',火:'Fire generates Earth',土:'Earth generates Metal',金:'Metal generates Water',水:'Water generates Wood'},es:{木:'Madera genera Fuego',火:'Fuego genera Tierra',土:'Tierra genera Metal',金:'Metal genera Agua',水:'Agua genera Madera'}};
const warStrategies=[
  ['先胜而后求战','Clarify the conditions for success before acting.','Aclara las condiciones de victoria antes de actuar.'],['上下同欲者胜','Create shared purpose before assigning roles.','Crea un propósito común antes de repartir funciones.'],['以正合，以奇胜','Build trust with a clear method, then create a distinctive breakthrough.','Genera confianza con un método claro y luego crea una diferencia.'],['知己知彼','Know your strengths, the other side and the context.','Conoce tus fortalezas, a la otra parte y el contexto.']
];
function namingSeed(name,date){return [...name].reduce((sum,char)=>sum+char.codePointAt(0),0)+Number(date.replaceAll('-',''))}
function pickSurname(name){const clean=name.trim();return surnameList.find(item=>item.re.test(clean))||{h:'林',p:'Lín'}}
function nameStrategy(number){if([1,8].includes(number))return warStrategies[0];if([2,6,9].includes(number))return warStrategies[1];if([3,5].includes(number))return warStrategies[2];return warStrategies[3]}
function createNames(original,date,intent){const nine=nineCalculation(date),chinese=calculateChineseLens(date),surname=pickSurname(original),base=chinese.element||'木',support=elementCycle[base],seed=namingSeed(original,date),ip=intentChars[intent],ep=elementChars[support],bp=elementChars[base],pairs=[[ip[seed%ip.length],ep[(seed+1)%ep.length]],[bp[(seed+2)%bp.length],ip[(seed+1)%ip.length]],[ep[(seed+3)%ep.length],ip[(seed+2)%ip.length]]];return{nine,chinese,surname,base,support,names:pairs.map(pair=>({hanzi:surname.h+pair[0].h+pair[1].h,pinyin:`${surname.p} ${pair[0].p} ${pair[1].p}`,chars:pair}))}}
function renderNaming(data){const ui=namingI18n[lang],strategy=nameStrategy(data.nine.number),profileRaw=nineSystem[lang][data.nine.number-1],profile=lang==='zh'?profileRaw:{name:profileRaw[0]};document.querySelector('#naming-context-label').textContent=ui.context;document.querySelector('#naming-context-title').textContent=`${data.nine.number}${lang==='zh'?'号人':' ·'} ${profile.name} · ${data.chinese.yearName} ${data.base}`;document.querySelector('#naming-context-copy').textContent=`${ui.sound} · ${ui.year} ${data.base} · ${ui.continuation} ${cycleText[lang][data.base]}. ${ui.notBazi}`;document.querySelector('#context-seal').textContent=data.surname.h;const cards=document.querySelector('#name-cards');cards.innerHTML='';data.names.forEach((name,index)=>{const meanings=name.chars.map(item=>`${item.h}：${item.m[lang]}`).join('；');const strategyTitle=strategy[0],strategyCopy=lang==='zh'?({1:'先明确成功条件，再行动。',2:'先建立共同目标，再安排角色。',3:'以稳定方法建立信任，再以独特之处形成突破。',4:'同时理解自己、对方与环境。'}[String([1,8].includes(data.nine.number)?1:[2,6,9].includes(data.nine.number)?2:[3,5].includes(data.nine.number)?3:4)]):strategy[lang==='en'?1:2];const card=document.createElement('article');card.className='name-card';card.dataset.order=String(index+1).padStart(2,'0');card.innerHTML=`<small>${ui.candidate} ${index+1}</small><h3>${name.hanzi}</h3><div class="name-pinyin">${name.pinyin}</div><p class="name-meaning">${meanings}</p><div class="name-meta"><span>${ui.system} ${data.nine.number}</span><span>${data.chinese.yearName}</span><span>${cycleText[lang][data.base]}</span></div><div class="war-note"><small>${ui.war}</small><h4>${strategyTitle}</h4><p>${strategyCopy}</p></div>`;cards.appendChild(card)});document.querySelector('#review-title').textContent=ui.review;document.querySelector('#review-copy').textContent=ui.reviewCopy;document.querySelector('#naming-result').hidden=false;document.querySelector('#naming-result').scrollIntoView({behavior:'smooth',block:'start'})}
function localizeNaming(){const ui=namingI18n[lang];document.querySelector('#naming-eyebrow').textContent=ui.eyebrow;document.querySelector('#naming-heading').innerHTML=ui.heading;document.querySelector('#naming-lead').textContent=ui.lead;document.querySelector('#original-name-label').textContent=ui.original;document.querySelector('#naming-birth-label').textContent=ui.birth;document.querySelector('#intent-label').textContent=ui.intent;[...document.querySelector('#naming-intent').options].forEach((option,index)=>option.textContent=ui.intents[index]);document.querySelector('#naming-submit').textContent=ui.submit;document.querySelector('#naming-privacy').textContent=ui.privacy}
document.querySelector('#naming-form').addEventListener('submit',event=>{event.preventDefault();renderNaming(createNames(document.querySelector('#original-name').value,document.querySelector('#naming-birth').value,document.querySelector('#naming-intent').value))});
document.querySelector('#birth').addEventListener('change',event=>{document.querySelector('#naming-birth').value=event.target.value});
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{localizeNaming();if(!document.querySelector('#naming-result').hidden)renderNaming(createNames(document.querySelector('#original-name').value,document.querySelector('#naming-birth').value,document.querySelector('#naming-intent').value))}));
localizeNaming();
const namingNavCopy={zh:'中文取名',en:'Chinese naming',es:'Nombre chino'};
function localizeNamingNav(){document.querySelector('#nav-naming').textContent=namingNavCopy[lang]}
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',localizeNamingNav));
localizeNamingNav();
