/*
 * Original Cultural Coordinate v0.2
 * A deterministic, browser-only storytelling model. It is not BaZi, an I Ching
 * divination method, a Maya calendar calculation, or a psychometric assessment.
 */
const talentContent={
  zh:{axes:['开拓','表达','构建','判断','洞察'],names:['开拓者','表达者','构建者','精炼者','洞察者'],elements:['木 · 生长与连接','火 · 可见与影响','土 · 稳定与承载','金 · 边界与品质','水 · 流动与智慧'],strengths:['创造与联结','表达与鼓舞','秩序与落实','判断与优化','洞察与适应'],descriptions:['你善于看见尚未成形的可能，并用行动把人、资源和机会连接起来。','你通过语言、热情和可见度影响环境，能够让想法被理解、被响应。','你擅长把模糊愿景变成可靠结构，以耐心、秩序和持续投入创造价值。','你重视边界、标准与品质，能从复杂信息中提炼关键并作出取舍。','你倾向先观察再行动，善于理解变化、关系和没有被直接说出的信息。'],balance:['在开启新方向之前，先选定一个能够持续完成的重点。','让热情配合倾听，并为重要承诺预留落实时间。','稳定之外也需要试验；允许小范围变化进入你的系统。','标准能够保护品质，也要为关系、探索和不确定性保留空间。','洞察需要转化为行动；为判断设定截止时间。'],strategyTitle:['先胜而后求战','以正合，以奇胜','上下同欲者胜','知彼知己','因敌变化而取胜'],strategy:['先判断优势、资源和退路，再启动真正重要的行动。','用清晰稳定的方法建立信任，再用独特表达创造突破。','让目标、角色和节奏一致，长期成果来自可以重复的协作。','重要决策前同时检查自己、对方与环境，减少只凭单一视角判断。','环境改变时及时调整路径，保持目的稳定而方法灵活。'],products:[['青衡 · 方向手珠','青玉、沉香木与罗盘故事对应你的开拓和连接倾向。'],['赤曜 · 行动力手珠','红玛瑙、虎眼石与火纹故事回应你的表达和行动力量。'],['青衡 · 方向手珠','沉静木质与罗盘象征帮助你把结构带向新的方向。'],['观澜 · 山水玉佩','山的定力和水的全局感对应你对品质与判断的重视。'],['观澜 · 山水玉佩','山水意象回应你在观察、变化与清晰判断中的优势。']],labels:{kicker:'你的核心文化原型',secondary:'辅助原型',number:'生日数',strength:'核心优势',balance:'平衡提醒',strategy:'东方战略提示',match:'与你的故事相匹配',link:'查看文化产品 →',note:'算法版本：原创文化坐标 v0.2。结果用于文化探索和自我反思，不是科学心理测评、命运预测或传统命理结论。'}},
  en:{axes:['Explore','Express','Build','Discern','Observe'],names:['Pioneer','Illuminator','Builder','Refiner','Seer'],elements:['Wood · growth & connection','Fire · visibility & influence','Earth · stability & support','Metal · boundaries & quality','Water · flow & wisdom'],strengths:['Creation & connection','Expression & inspiration','Order & delivery','Judgment & refinement','Insight & adaptation'],descriptions:['You see emerging possibilities and connect people, resources and opportunities through action.','You influence through language, enthusiasm and visibility, helping ideas become understood and felt.','You turn an uncertain vision into a dependable structure through patience, order and sustained effort.','You value boundaries, standards and quality, distilling what matters from complex information.','You tend to observe before acting and notice change, relationships and what remains unspoken.'],balance:['Before opening another direction, choose one priority you can complete.','Pair enthusiasm with listening and reserve time to deliver on important promises.','Stability also needs experiments; allow small, reversible changes into your system.','Standards protect quality, but leave room for relationships, discovery and uncertainty.','Turn insight into action by giving important decisions a deadline.'],strategyTitle:['Win before engaging','The orthodox and unexpected','Shared purpose creates strength','Know both sides','Adapt to change'],strategy:['Assess advantage, resources and a safe exit before beginning consequential action.','Build trust through a clear, steady method, then create breakthrough through distinctive expression.','Align goals, roles and rhythm; durable results come from repeatable collaboration.','Before deciding, examine yourself, the other side and the environment together.','Keep the purpose steady while adapting the path as conditions change.'],products:[['Qingheng · Direction Bracelet','Jade, sandalwood and a compass echo your drive to explore and connect.'],['Chiyao · Action Bracelet','Red agate, tiger eye and a flame echo your expressive energy.'],['Qingheng · Direction Bracelet','Quiet wood and a compass help carry structure toward a new direction.'],['Guanlan · Mountain & Water Pendant','Mountain steadiness and water perspective reflect your care for sound judgment.'],['Guanlan · Mountain & Water Pendant','The landscape imagery reflects your strength in observation and adaptation.']],labels:{kicker:'Your core cultural archetype',secondary:'Supporting archetype',number:'Birth number',strength:'Core strength',balance:'Balancing invitation',strategy:'Eastern strategy prompt',match:'Matched to your story',link:'View cultural products →',note:'Algorithm: Original Cultural Coordinate v0.2. For cultural exploration and reflection—not a psychometric assessment, prediction, or traditional destiny calculation.'}},
  es:{axes:['Explorar','Expresar','Construir','Discernir','Observar'],names:['Pionero','Iluminador','Constructor','Refinador','Observador'],elements:['Madera · crecimiento y conexión','Fuego · visibilidad e influencia','Tierra · estabilidad y apoyo','Metal · límites y calidad','Agua · fluidez y sabiduría'],strengths:['Creación y conexión','Expresión e inspiración','Orden y ejecución','Criterio y mejora','Perspicacia y adaptación'],descriptions:['Ves posibilidades emergentes y conectas personas, recursos y oportunidades mediante la acción.','Influyes mediante lenguaje, entusiasmo y visibilidad, ayudando a que las ideas sean comprendidas.','Transformas una visión incierta en una estructura fiable mediante paciencia, orden y constancia.','Valoras límites, estándares y calidad, distinguiendo lo esencial dentro de información compleja.','Sueles observar antes de actuar y percibes cambios, relaciones y lo que no se dice directamente.'],balance:['Antes de abrir otra dirección, elige una prioridad que puedas completar.','Combina entusiasmo con escucha y reserva tiempo para cumplir tus compromisos.','La estabilidad también necesita experimentos y pequeños cambios reversibles.','Los estándares protegen la calidad, pero deja espacio para relaciones y descubrimiento.','Convierte la percepción en acción dando una fecha límite a tus decisiones.'],strategyTitle:['Vencer antes de combatir','Lo directo y lo inesperado','La unidad del propósito','Conocer ambas partes','Adaptarse al cambio'],strategy:['Evalúa ventaja, recursos y salida antes de iniciar una acción importante.','Genera confianza con un método claro y crea avances con una expresión distintiva.','Alinea objetivos, funciones y ritmo; los resultados duraderos nacen de una colaboración repetible.','Antes de decidir, examina a la vez tu posición, la otra parte y el entorno.','Mantén estable el propósito y adapta el camino cuando cambien las condiciones.'],products:[['Qingheng · Pulsera de dirección','El jade, el sándalo y la brújula reflejan tu impulso de explorar y conectar.'],['Chiyao · Pulsera de acción','El ágata roja, el ojo de tigre y la llama reflejan tu energía expresiva.'],['Qingheng · Pulsera de dirección','La madera serena y la brújula llevan la estructura hacia una nueva dirección.'],['Guanlan · Colgante de montaña y agua','La firmeza de la montaña y la perspectiva del agua reflejan tu criterio.'],['Guanlan · Colgante de montaña y agua','El paisaje refleja tu capacidad de observación y adaptación.']],labels:{kicker:'Tu arquetipo cultural central',secondary:'Arquetipo de apoyo',number:'Número natal',strength:'Fortaleza central',balance:'Invitación al equilibrio',strategy:'Clave de estrategia oriental',match:'Una pieza para tu historia',link:'Ver productos culturales →',note:'Algoritmo: Coordenada Cultural Original v0.2. Para exploración y reflexión; no es una prueba psicométrica, predicción ni cálculo tradicional del destino.'}}
};

const phaseTwoContent={
  zh:{demo:'从“知己”开始：输入生日与当前关注，获得三层文化坐标和一份自我观察行动图。',focus:[['talent','天赋与自我'],['career','事业与转型'],['relationship','关系与合作'],['balance','身心平衡']],lens:['原创天赋坐标','中国历法视角','玛雅卓尔金视角'],original:'以生日数字生成五个可复核的原创叙事维度，不属于传统命理。',chinese:'以中国农历年干支呈现生肖和年干五行，仅是年象征，不是完整八字。',maya:'卓尔金由13个数字与20个日名循环组合成260个独特日期；此处显示历法坐标，不作命运断言。',pathLabel:'中西结合 · 助己助人',pathTitle:'先知己，再知彼',path:'依据你的 XMind 方法重新组织：先认识自己的资源与模式，再观察环境、关系和真正目标。网页只提供自我反思，不自动诊断创伤或疾病。',steps:['算','看','问','观'],stepTitles:['三层文化坐标','观察当下模式','提出关键问题','形成行动策略'],prompts:{talent:['留意你在没有外界要求时，最自然会使用哪一种能力。','如果只能保留三项优势，你希望别人如何描述你？','选择一项优势，在未来七天帮助一个具体的人或目标。'],career:['观察哪些任务让你投入，哪些环境持续消耗你的注意力。','当前目标、资源、阻力和可接受的代价分别是什么？','先做一次成本可控的小试验，再依据结果决定是否扩大行动。'],relationship:['观察沟通中你更常主动、迎合、回避，还是先判断后回应。','你真正需要对方理解什么？对方可能在保护什么需要？','先明确共同目标和边界，再讨论方法与分工。'],balance:['观察睡眠、呼吸、节奏和情绪变化，但不凭身体特征推断疾病。','什么事情正在消耗你？什么人、习惯或环境能够补充资源？','选择一个可持续的小调整；如持续困扰影响生活，寻求合格专业人士。']},note:'阶段二 · 文化探索版。中国历法依据浏览器农历转换与干支年；玛雅模块采用GMT相关常数584283显示卓尔金日期。结果不自动推断疾病、创伤、财富或命运。'},
  en:{demo:'Begin by knowing yourself: enter a birth date and current focus to receive three cultural coordinates and a reflection-to-action map.',focus:[['talent','Talent & self'],['career','Career & transition'],['relationship','Relationships & collaboration'],['balance','Well-being & balance']],lens:['Original talent coordinate','Chinese calendar lens','Maya Tzolk’in lens'],original:'Five reproducible narrative dimensions generated from birth-date digits; this is not a traditional destiny system.',chinese:'Shows the lunar-year stem, branch, zodiac and stem element. This is a year symbol, not a complete BaZi reading.',maya:'The Tzolk’in combines 13 numbers with 20 day names into 260 unique dates. This displays a calendar coordinate, not a prediction.',pathLabel:'East–West integration · help self and others',pathTitle:'Know yourself, then understand the other',path:'Reframed from your XMind method: recognize your resources and patterns first, then observe context, relationships and the real objective. The website supports reflection and does not diagnose illness or trauma.',steps:['Calculate','See','Ask','Observe'],stepTitles:['Three cultural coordinates','Notice the present pattern','Ask the key question','Form an action strategy'],prompts:{talent:['Notice which ability appears naturally when no one is directing you.','If you could keep only three strengths, how would you want others to describe you?','Use one strength to help a concrete person or goal within seven days.'],career:['Notice which tasks absorb you and which settings continually drain attention.','What are the goal, resources, obstacles and acceptable cost?','Run one contained experiment, then decide whether to expand based on evidence.'],relationship:['Notice whether you initiate, accommodate, avoid or assess before responding.','What do you need understood, and what need might the other person be protecting?','Clarify the shared goal and boundaries before discussing method and roles.'],balance:['Observe sleep, breathing, pace and emotion without inferring illness from appearance.','What is draining you, and which people, habits or settings restore resources?','Choose one sustainable adjustment; seek a qualified professional if distress persists.']},note:'Phase 2 cultural exploration. The Chinese lens uses browser lunar-calendar conversion; the Maya lens uses GMT correlation 584283 for the Tzolk’in coordinate. It does not infer illness, trauma, wealth or destiny.'},
  es:{demo:'Empieza por conocerte: introduce fecha de nacimiento y enfoque actual para obtener tres coordenadas culturales y un mapa de reflexión a acción.',focus:[['talent','Talento y yo'],['career','Carrera y transición'],['relationship','Relaciones y colaboración'],['balance','Bienestar y equilibrio']],lens:['Coordenada original','Perspectiva del calendario chino','Perspectiva Tzolk’in maya'],original:'Cinco dimensiones narrativas reproducibles generadas con la fecha; no es un sistema tradicional del destino.',chinese:'Muestra tronco, rama, zodiaco y elemento del año lunar. Es un símbolo anual, no una lectura BaZi completa.',maya:'El Tzolk’in combina 13 números y 20 nombres para formar 260 fechas únicas. Aquí se muestra una coordenada, no una predicción.',pathLabel:'Integración Oriente–Occidente · ayudarse y ayudar',pathTitle:'Conócete y luego comprende al otro',path:'Reorganizado desde tu método XMind: primero reconocer recursos y patrones; después observar contexto, relaciones y objetivo real. La web favorece reflexión y no diagnostica enfermedad ni trauma.',steps:['Calcular','Ver','Preguntar','Observar'],stepTitles:['Tres coordenadas culturales','Notar el patrón presente','Plantear la pregunta clave','Formar una estrategia'],prompts:{talent:['Observa qué capacidad aparece naturalmente cuando nadie te dirige.','Si conservaras solo tres fortalezas, ¿cómo querrías que otros te describieran?','Usa una fortaleza para ayudar a una persona u objetivo concreto en siete días.'],career:['Observa qué tareas te absorben y qué entornos agotan tu atención.','¿Cuáles son objetivo, recursos, obstáculos y coste aceptable?','Haz un experimento controlado y decide con sus resultados.'],relationship:['Observa si inicias, complaces, evitas o evalúas antes de responder.','¿Qué necesitas que se comprenda y qué necesidad protege la otra persona?','Aclara objetivo común y límites antes de hablar de método y funciones.'],balance:['Observa sueño, respiración, ritmo y emoción sin inferir enfermedad por la apariencia.','¿Qué te agota y qué personas, hábitos o entornos restauran recursos?','Elige un cambio sostenible; busca ayuda profesional cualificada si el malestar persiste.']},note:'Fase 2 de exploración cultural. La perspectiva china usa conversión lunar del navegador; la maya usa correlación GMT 584283. No infiere enfermedad, trauma, riqueza ni destino.'}
};
const nineSystem={
  zh:[
    {name:'创新领导型',strength:'创新、开创与带领',copy:'你倾向从无到有地推动事情，重视自主、效率与方向感。',balance:'行动前多听一个不同意见，把“我来决定”升级为“我来带领大家决定”。',strategy:'先明确主攻方向，再集中资源形成第一个可见成果。',product:['青衡 · 方向手珠','罗盘象征方向，木与青玉回应开创和生长。']},
    {name:'沟通合作型',strength:'沟通、协调与细节感',copy:'你善于理解他人、连接不同立场，并在合作中发现细节。',balance:'同理不等于迎合；重要决定需要表达自己的真实边界。',strategy:'先找到共同利益，再安排角色与沟通节奏。',product:['观澜 · 山水玉佩','山水的相依关系回应协调、倾听与平衡。']},
    {name:'热情表现型',strength:'表达、感染与创造',copy:'你通过热情、语言和创造力点亮环境，容易让想法被看见。',balance:'让表达配合倾听，并把灵感落实为可以完成的作品。',strategy:'用鲜明表达打开局面，再用稳定交付建立长期影响。',product:['赤曜 · 行动力手珠','红玛瑙与火纹回应热情、表达和行动。']},
    {name:'规划稳定型',strength:'结构、秩序与可靠',copy:'你重视数据、规划和稳定，擅长把复杂事情变成清晰步骤。',balance:'安全感之外也需要试验，为计划留下小范围调整空间。',strategy:'把目标拆成阶段、标准和责任人，以稳定节奏推进。',product:['青衡 · 方向手珠','沉香木的稳定与罗盘的规划感对应你的结构优势。']},
    {name:'自由冒险型',strength:'探索、变化与适应',copy:'你需要空间、体验和新鲜感，擅长在变化中发现新机会。',balance:'自由需要承担结果；为重要目标建立最少但清晰的承诺。',strategy:'先以低成本探索多个方向，再集中投入最有证据的一条。',product:['青衡 · 方向手珠','罗盘象征远行、探索，以及自由中的方向感。']},
    {name:'完美智慧型',strength:'责任、关怀与优化',copy:'你重视品质与责任，愿意投入心力帮助事情和关系变得更好。',balance:'关怀不等于包办；降低过度要求，为自己和他人留出成长空间。',strategy:'先定义“足够好”的标准，再把责任分配给合适的人。',product:['观澜 · 山水玉佩','山的责任与水的包容回应关怀和智慧。']},
    {name:'人缘博学型',strength:'研究、连接与求真',copy:'你喜欢钻研、理解真相，也容易通过知识与专业连接人群。',balance:'追求答案时保留耐心，避免因怀疑或过度分析错过行动。',strategy:'先验证关键假设，再把研究转化为别人能够使用的结论。',product:['观澜 · 山水玉佩','山水全局意象回应钻研、观察与求真。']},
    {name:'梦想责任型',strength:'目标、担当与执行',copy:'你重视成果和责任，具有把愿景变成现实的推动力。',balance:'责任不必全部自己承担；让坦率配合尊重和授权。',strategy:'明确最终战果、关键资源和责任边界，集中力量完成主目标。',product:['赤曜 · 行动力手珠','虎眼石与火纹回应目标感、担当和执行力。']},
    {name:'丰富乐享型',strength:'整合、助人和广阔视角',copy:'你容易看见整体，愿意帮助他人，并从丰富体验中提炼意义。',balance:'理想需要落地；缩小范围、明确优先级，避免同时承担过多。',strategy:'从全局选择最值得帮助的对象，再建立可持续的投入方式。',product:['观澜 · 山水玉佩','山水相生的整体感回应助人、整合与长远视角。']}
  ],
  en:[
    ['Innovative Leader','Innovation, initiative & leadership','You tend to create from zero and value autonomy, efficiency and direction.'],['Collaborative Communicator','Communication, coordination & detail','You connect perspectives and notice important details through collaboration.'],['Enthusiastic Expressor','Expression, influence & creativity','You energize environments through language, warmth and visible creativity.'],['Stable Planner','Structure, order & reliability','You turn complexity into clear steps through data, planning and consistency.'],['Free Explorer','Exploration, change & adaptability','You need room to experience, explore and discover opportunities in change.'],['Wise Improver','Responsibility, care & refinement','You value quality and invest energy in helping people and systems improve.'],['Connected Scholar','Research, networks & truth-seeking','You pursue understanding and connect people through knowledge and expertise.'],['Responsible Achiever','Goals, ownership & execution','You carry responsibility and turn ambitious vision into tangible outcomes.'],['Abundant Integrator','Integration, contribution & perspective','You see the whole, support others and find meaning across varied experience.']
  ],
  es:[
    ['Líder innovador','Innovación, iniciativa y liderazgo','Tiendes a crear desde cero y valoras autonomía, eficiencia y dirección.'],['Comunicador colaborativo','Comunicación, coordinación y detalle','Conectas perspectivas y detectas detalles importantes al colaborar.'],['Expresor entusiasta','Expresión, influencia y creatividad','Energizas el entorno mediante lenguaje, calidez y creatividad visible.'],['Planificador estable','Estructura, orden y fiabilidad','Conviertes complejidad en pasos claros mediante datos y planificación.'],['Explorador libre','Exploración, cambio y adaptación','Necesitas espacio para experimentar y descubrir oportunidades en el cambio.'],['Mejorador sabio','Responsabilidad, cuidado y mejora','Valoras la calidad y ayudas a mejorar personas y sistemas.'],['Erudito conectado','Investigación, redes y búsqueda de verdad','Buscas comprensión y conectas personas mediante conocimiento.'],['Realizador responsable','Objetivos, responsabilidad y ejecución','Asumes responsabilidad y conviertes visión ambiciosa en resultados.'],['Integrador abundante','Integración, contribución y perspectiva','Ves el conjunto, apoyas a otros y encuentras sentido en experiencias diversas.']
  ]
};
function digitalRoot(n){let value=Math.abs(Number(n));while(value>9)value=String(value).split('').reduce((a,d)=>a+Number(d),0);return value||9}
function calculateTalent(dateString){const [year,month,day]=dateString.split('-').map(Number);const date=new Date(Date.UTC(year,month-1,day));const start=new Date(Date.UTC(year,0,1));const dayOfYear=Math.floor((date-start)/86400000)+1;const root=digitalRoot(`${year}${String(month).padStart(2,'0')}${String(day).padStart(2,'0')}`);const weekday=date.getUTCDay();const seeds=[year+dayOfYear,month*day+root*11,dayOfYear+year%100,weekday*31+day*7+month,Math.floor(date.getTime()/86400000)+root*17];const scores=seeds.map((seed,i)=>52+((Math.abs(seed)*(i*6+11)+root*7+dayOfYear)%43));const ranking=scores.map((score,index)=>({score,index})).sort((a,b)=>b.score-a.score||a.index-b.index);return{scores,primary:ranking[0].index,secondary:ranking[1].index,root}}
function calculateChineseLens(dateString){const [year,month,day]=dateString.split('-').map(Number);const date=new Date(Date.UTC(year,month-1,day,12));const parts=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).formatToParts(date);const get=type=>parts.find(part=>part.type===type)?.value||'';const yearName=get('yearName');const stem=yearName[0]||'',branch=yearName[1]||'';const stems='甲乙丙丁戊己庚辛壬癸',branches='子丑寅卯辰巳午未申酉戌亥',elements=['木','木','火','火','土','土','金','金','水','水'],animals=['鼠','牛','虎','兔','龙','蛇','马','羊','猴','鸡','狗','猪'];const stemIndex=stems.indexOf(stem),branchIndex=branches.indexOf(branch);return{yearName,lunar:`${get('month')}${get('day')}日`,element:elements[stemIndex]||'',animal:animals[branchIndex]||'',yinYang:stemIndex%2===0?'阳':'阴',stemIndex,branchIndex}}
function calculateMayaLens(dateString){const [year,month,day]=dateString.split('-').map(Number);const date=new Date(Date.UTC(year,month-1,day));const julianDay=Math.floor(date.getTime()/86400000+2440587.5+0.5);const longCountDays=julianDay-584283;const signs=['Imix’','Ik’','Ak’bal','K’an','Chikchan','Kimi','Manik’','Lamat','Muluk','Ok','Chuwen','Eb’','B’en','Ix','Men','K’ib’','Kab’an','Etz’nab’','Kawak','Ajaw'];const number=((longCountDays+3)%13+13)%13+1;const sign=signs[((longCountDays+19)%20+20)%20];return{number,sign,longCountDays}}
function nineCalculation(dateString){const digits=dateString.replaceAll('-','').split('').map(Number);const total=digits.reduce((sum,value)=>sum+value,0);let reduced=total;const stages=[total];while(reduced>9){reduced=String(reduced).split('').reduce((sum,value)=>sum+Number(value),0);stages.push(reduced)}return{digits,total,number:reduced,display:`${digits.join('+')}=${stages.join('→')}`}}
function renderNineSystem(dateString,result,t,c){const calc=nineCalculation(dateString),raw=nineSystem[lang][calc.number-1],profile=lang==='zh'?raw:{name:raw[0],strength:raw[1],copy:raw[2]},focus=document.querySelector('#focus').value;const numberLabel=lang==='zh'?`${calc.number}号人`:lang==='en'?`Number ${calc.number}`:`Número ${calc.number}`;const systemLabel=lang==='zh'?'九数主系统':lang==='en'?'Primary nine-number system':'Sistema principal de nueve números';const balanceTitle=lang==='zh'?'成长提醒':lang==='en'?'Growth invitation':'Invitación de crecimiento';const auxLabel=lang==='zh'?'辅助五维':lang==='en'?'Supporting dimensions':'Dimensiones de apoyo';const ranking=result.scores.map((score,index)=>({score,index})).sort((a,b)=>b.score-a.score);document.querySelector('#report-kicker').textContent=systemLabel;document.querySelector('#result-title').textContent=`${numberLabel} · ${profile.name}`;document.querySelector('#result-copy').textContent=profile.copy;document.querySelector('#result-element').textContent=`${systemLabel} · ${calc.number}`;document.querySelector('#result-secondary').textContent=`${auxLabel} · ${t.axes[ranking[0].index]} + ${t.axes[ranking[1].index]}`;document.querySelector('#result-number').textContent=calc.display;document.querySelector('#result-strength').textContent=profile.strength;document.querySelector('#strength-copy').textContent=profile.copy;document.querySelector('#balance-title').textContent=balanceTitle;document.querySelector('#balance-copy').textContent=lang==='zh'?profile.balance:t.balance[(calc.number-1)%5];document.querySelector('#strategy-title').textContent=lang==='zh'?'知己知彼':t.strategyTitle[(calc.number-1)%5];document.querySelector('#strategy-copy').textContent=lang==='zh'?profile.strategy:t.strategy[(calc.number-1)%5];const productIndex=[0,2,1,0,0,2,2,1,2][calc.number-1];const product=lang==='zh'?profile.product:t.products[productIndex];document.querySelector('#match-title').textContent=product[0];document.querySelector('#match-copy').textContent=product[1];document.querySelector('#original-lens-label').textContent=systemLabel;document.querySelector('#original-lens-title').textContent=`${numberLabel} · ${profile.name}`;document.querySelector('#original-lens-copy').textContent=`${calc.display} · ${profile.strength}`;document.querySelector('#step-calc-copy').textContent=`${calc.display} → ${numberLabel} · ${profile.name}`;document.querySelector('#algorithm-note').textContent=lang==='zh'?'阶段二 · 九数主系统。完整生日逐位相加并反复化简到1—9；五维坐标、中国干支年与玛雅卓尔金为辅助视角。结果不自动推断疾病、创伤、财富或命运。':lang==='en'?'Phase 2 · primary nine-number system. All birth-date digits are summed and reduced to 1–9; the other cultural coordinates are supporting lenses. It does not infer illness, trauma, wealth or destiny.':'Fase 2 · sistema principal de nueve números. Se suman todos los dígitos de la fecha y se reducen a 1–9; las otras perspectivas son auxiliares. No infiere enfermedad, trauma, riqueza ni destino.'}
function renderPhaseTwo(dateString,result,t){const c=phaseTwoContent[lang],chinese=calculateChineseLens(dateString),maya=calculateMayaLens(dateString),focus=document.querySelector('#focus').value;const stems=['Jia','Yi','Bing','Ding','Wu','Ji','Geng','Xin','Ren','Gui'],branches=['Zi','Chou','Yin','Mao','Chen','Si','Wu','Wei','Shen','You','Xu','Hai'],elements={en:['Wood','Wood','Fire','Fire','Earth','Earth','Metal','Metal','Water','Water'],es:['Madera','Madera','Fuego','Fuego','Tierra','Tierra','Metal','Metal','Agua','Agua']},animals={en:['Rat','Ox','Tiger','Rabbit','Dragon','Snake','Horse','Goat','Monkey','Rooster','Dog','Pig'],es:['Rata','Buey','Tigre','Conejo','Dragón','Serpiente','Caballo','Cabra','Mono','Gallo','Perro','Cerdo']};const chineseTitle=lang==='zh'?`${chinese.yearName} · ${chinese.element}${chinese.animal}`:`${stems[chinese.stemIndex]}-${branches[chinese.branchIndex]} · ${elements[lang][chinese.stemIndex]} ${animals[lang][chinese.branchIndex]}`;const chineseDetail=lang==='zh'?`${chinese.lunar} · ${chinese.yinYang}${chinese.element}`:chinese.yearName;document.querySelector('#original-lens-label').textContent=c.lens[0];document.querySelector('#original-lens-title').textContent=t.names[result.primary];document.querySelector('#original-lens-copy').textContent=c.original;document.querySelector('#chinese-lens-label').textContent=c.lens[1];document.querySelector('#chinese-lens-title').textContent=chineseTitle;document.querySelector('#chinese-lens-copy').textContent=`${c.chinese} ${chineseDetail}`;document.querySelector('#maya-lens-label').textContent=c.lens[2];document.querySelector('#maya-lens-title').textContent=`${maya.number} ${maya.sign}`;document.querySelector('#maya-lens-copy').textContent=c.maya;document.querySelector('#path-label').textContent=c.pathLabel;document.querySelector('#path-title').textContent=c.pathTitle;document.querySelector('#path-copy').textContent=c.path;const ids=['calc','see','ask','observe'];ids.forEach((id,i)=>{document.querySelector(`#step-${id}-label`).textContent=c.steps[i];document.querySelector(`#step-${id}-title`).textContent=c.stepTitles[i]});document.querySelector('#step-calc-copy').textContent=`${t.names[result.primary]} · ${chineseTitle} · ${maya.number} ${maya.sign}`;document.querySelector('#step-see-copy').textContent=c.prompts[focus][0];document.querySelector('#step-ask-copy').textContent=c.prompts[focus][1];document.querySelector('#step-observe-copy').textContent=c.prompts[focus][2];document.querySelector('#algorithm-note').textContent=c.note;renderNineSystem(dateString,result,t,c)}
function localizePhaseTwo(){const c=phaseTwoContent[lang];document.querySelector('[data-i18n="demoText"]').textContent=c.demo;document.querySelector('[data-i18n="demoTitle"]').textContent=lang==='zh'?'生成你的九数天赋图谱':lang==='en'?'Generate your nine-number Talent Atlas':'Genera tu Atlas de nueve números';document.querySelector('[data-i18n="generate"]').textContent=lang==='zh'?'启动九数轮 →':lang==='en'?'Spin the nine-number wheel →':'Girar la rueda de nueve números →';if(!wheelBusy&&!document.querySelector('#oracle-stage').classList.contains('revealed'))document.querySelector('#wheel-action').textContent=lang==='zh'?'点击转动':lang==='en'?'Tap to spin':'Toca para girar';const select=document.querySelector('#focus');[...select.options].forEach((option,i)=>option.textContent=c.focus[i][1])}
function polygonPoints(scores){const center=[160,150],max=108;return scores.map((score,i)=>{const angle=-Math.PI/2+i*Math.PI*2/5;const radius=max*score/100;return`${center[0]+Math.cos(angle)*radius},${center[1]+Math.sin(angle)*radius}`}).join(' ')}
function buildRadar(t,scores){const grid=document.querySelector('#radar-grid');grid.innerHTML='';for(let level=1;level<=4;level++){const points=Array.from({length:5},(_,i)=>{const a=-Math.PI/2+i*Math.PI*2/5,r=108*level/4;return`${160+Math.cos(a)*r},${150+Math.sin(a)*r}`}).join(' ');grid.insertAdjacentHTML('beforeend',`<polygon class="radar-line" points="${points}"></polygon>`)}const labels=document.querySelector('#radar-labels');labels.innerHTML='';t.axes.forEach((name,i)=>{const a=-Math.PI/2+i*Math.PI*2/5,x=160+Math.cos(a)*132,y=154+Math.sin(a)*124;labels.insertAdjacentHTML('beforeend',`<line class="radar-axis" x1="160" y1="150" x2="${160+Math.cos(a)*108}" y2="${150+Math.sin(a)*108}"></line><text class="radar-text" x="${x}" y="${y}">${name}</text>`)});document.querySelector('#radar-shape').setAttribute('points',polygonPoints(scores))}
function renderTalent(dateString){const t=talentContent[lang],r=calculateTalent(dateString),p=r.primary,s=r.secondary;document.querySelector('#report-kicker').textContent=t.labels.kicker;document.querySelector('#result-title').textContent=t.names[p];document.querySelector('#result-copy').textContent=t.descriptions[p];document.querySelector('#result-element').textContent=t.elements[p];document.querySelector('#result-secondary').textContent=`${t.labels.secondary} · ${t.names[s]}`;document.querySelector('#result-number').textContent=`${t.labels.number} · ${r.root}`;document.querySelector('#strength-label').textContent=t.labels.strength;document.querySelector('#result-strength').textContent=t.strengths[p];document.querySelector('#strength-copy').textContent=t.descriptions[p];document.querySelector('#balance-label').textContent=t.labels.balance;document.querySelector('#balance-title').textContent=t.axes[r.scores.indexOf(Math.min(...r.scores))];document.querySelector('#balance-copy').textContent=t.balance[p];document.querySelector('#strategy-label').textContent=t.labels.strategy;document.querySelector('#strategy-title').textContent=t.strategyTitle[p];document.querySelector('#strategy-copy').textContent=t.strategy[p];document.querySelector('#match-label').textContent=t.labels.match;document.querySelector('#match-title').textContent=t.products[p][0];document.querySelector('#match-copy').textContent=t.products[p][1];document.querySelector('#match-link').textContent=t.labels.link;const bars=document.querySelector('#score-bars');bars.innerHTML='';t.axes.forEach((name,i)=>bars.insertAdjacentHTML('beforeend',`<div class="score-item"><div><span>${name}</span><b>${r.scores[i]}</b></div><div class="score-track"><div class="score-fill" style="width:${r.scores[i]}%"></div></div></div>`));buildRadar(t,r.scores);renderPhaseTwo(dateString,r,t);const report=document.querySelector('#result');report.hidden=false;report.scrollIntoView({behavior:'smooth',block:'start'})}
let wheelRotation=0,wheelBusy=false;
function spinTalentWheel(dateString){
  if(wheelBusy)return;
  wheelBusy=true;
  const calc=nineCalculation(dateString),stage=document.querySelector('#oracle-stage'),wheel=document.querySelector('#nine-wheel'),action=document.querySelector('#wheel-action'),status=document.querySelector('#wheel-status');
  stage.classList.remove('revealed');stage.classList.add('spinning');
  action.textContent=lang==='zh'?'玄轮缓缓运转…':lang==='en'?'The wheel is turning…':'La rueda está girando…';
  status.textContent=lang==='zh'?'九数坐标正在汇聚':lang==='en'?'The nine-number coordinate is forming':'La coordenada está tomando forma';
  const normalized=((wheelRotation%360)+360)%360,desired=(360-(calc.number-1)*40)%360,delta=((desired-normalized+360)%360)+1080;
  wheelRotation+=delta;
  requestAnimationFrame(()=>{wheel.style.transform=`rotate(${wheelRotation}deg)`});
  const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches,delay=reduced?80:5250;
  setTimeout(()=>{stage.classList.remove('spinning');stage.classList.add('revealed');wheelBusy=false;action.textContent=lang==='zh'?`${calc.number}号显现`:lang==='en'?`Number ${calc.number} revealed`:`Número ${calc.number} revelado`;status.textContent=calc.display;renderTalent(dateString)},delay)
}
document.querySelector('#birth-form').addEventListener('submit',event=>{event.preventDefault();spinTalentWheel(document.querySelector('#birth').value)});
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{localizePhaseTwo();if(!document.querySelector('#result').hidden)renderTalent(document.querySelector('#birth').value)}));
localizePhaseTwo();
